### ISSUE TITLE
Sparklyr + livy fails for java  memory heap error

### ISSUE THREAD

**Issue by jodom961** [sparklyr/sparklyr#3099]
# Reporting an Issue with sparklyr

```r
SPARK_VERSION <- "2.3.2"

# your reproducible example here

sparklyr::livy_install(version="0.7.1", spark_version=SPARK_VERSION)

config <- livy_config(username="username", password="supersecretpass",negotiate = TRUE, 
                      custom_headers = list("X-Requested-By"="username"))

config$sparklyr.livy.jar = list("hdfs://user/jake/sparklyr-2.3-2.11.jar")

sc <- spark_connect(master = "http://some.remote.host.com:8998/", method = "livy", config = config, version=SPARK_VERSION, spark_home = "/usr/share/spark-2.3")

```

### Error

```
Error in h(simpleError(msg, call)) : 
  Failed to initialize livy connection: Failed to execute Livy statement with error: java.lang.OutOfMemoryError: Java heap space
Traceback: 

callstack:
spark_connect(master = "http://some.remote.host.com:8998/", method = "livy", config = config, version = SPARK_VERSION, spark_home = "/usr/share/spark-2.3")
initialize_connection(scon)
initialize_connection.livy_connection(scon)
withCallingHandlers({
    session <- tryCatch({
        invoke_static(sc, "org.apache.spark.sql.SparkSession", "builder") %>% invoke("%>%", list("enableHiveSupport"), list("getOrCreate"))
    }, error = function(e) {
        NULL
    })
    sc$state$spark_context <- tryCatch({
        invoke(session, "sparkContext")
    }, error = function(e) {
        invoke_static(sc, "org.apache.spark.SparkContext", "getOrCreate")
    })
    sc$state$java_context <- invoke_static(sc, "org.apache.spark.api.java.JavaSparkContext", "fromSparkContext", spark_context(sc))
    sc$state$spark_version <- spark_version(sc)
    sc$state$hive_context <- session %||% create_hive_context(sc)
    if (spark_version(sc) < "2.0.0") {
        params <- connection_config(sc, "spark.sql.")
        apply_config(hive_context, params, "setConf", "spark.sql.")
    }
    sc
}, error = function(err) {
    stop("Failed to initialize livy connection: ", err$message, "\n\ncallstack:\n", paste(sys.calls(), collapse = "\n"))
})
tryCatch({
    invoke(session, "sparkContext")
}, error = function(e) {
    invoke_static(sc, "org.apache.spark.SparkContext", "getOrCreate")
})
tryCatchList(expr, classes, parentenv, handlers)
tryCatchOne(expr, names, parentenv, handlers[[1]])
value[[3]](cond)
invoke_static(sc, "org.apache.spark.SparkContext", "getOrCreate")
invoke_static.livy_connection(sc, "org.apache.spark.SparkContext", "getOrCreate")
livy_invoke_statement_fetch(sc, TRUE, class, method, ...)
livy_invoke_statement(sc, statement)
livy_post_statement(sc, statement$code)
withr::with_options(list(warning.length = 8000), {
    stop("Failed to execute Livy statement with error: ", if (is.null(statementReponse$output$evalue)) {
        jsonlite::toJSON(statementReponse)
    }
    else {
        statementReponse$output$evalue
    }, "\nTraceback: ", paste(statementReponse$output$traceback, collapse = ""))
})
force(code)
stop("Failed to execute Livy statement with error: ", if (is.null(statementReponse$output$evalue)) {
    jsonlite::toJSON(statementReponse)
} else {
    statementReponse$output$evalue
}, "\nTraceback: ", paste(statementReponse$output$traceback, collapse = ""))
.handleSimpleError(function (err) 
{
    stop("Failed to initialize livy connection: ", err$message, "\n\ncallstack:\n", paste(sys.calls(), collapse = "\n"))
}, "Failed to execute Livy statement with error: java.lang.OutOfMemoryError: Java heap space\nTraceback: ", base::quote(force(code)))
h(simpleError(msg, call))
```

### Session Info 
```R
R version 3.6.3 (2020-02-29)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Debian GNU/Linux 10 (buster)

Matrix products: default
BLAS:   /usr/lib/x86_64-linux-gnu/blas/libblas.so.3.8.0
LAPACK: /usr/lib/x86_64-linux-gnu/lapack/liblapack.so.3.8.0

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8     LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8    LC_PAPER=en_US.UTF-8      
 [8] LC_NAME=C                  LC_ADDRESS=C               LC_TELEPHONE=C             LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] sparklyr_1.6.2  sys_3.4              

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.6        pillar_1.6.1      compiler_3.6.3    dbplyr_2.1.1      plyr_1.8.6        r2d3_0.2.5        RJDBC_0.2-8       base64enc_0.1-3   tools_3.6.3       digest_0.6.27    
[11] jsonlite_1.7.2    lifecycle_1.0.0   tibble_3.1.2      pkgconfig_2.0.3   rlang_0.4.11      DBI_1.1.1         rstudioapi_0.13   rJava_1.0-4       dplyr_1.0.6       httr_1.4.2       
[21] generics_0.1.0    vctrs_0.3.8       htmlwidgets_1.5.3 rprojroot_2.0.2   DT_0.18           tidyselect_1.1.1  glue_1.4.2        forge_0.2.0       R6_2.5.0          fansi_0.4.2      
[31] tidyr_1.1.3       purrr_0.3.4       magrittr_2.0.1    ellipsis_0.3.2    htmltools_0.5.1.1 assertthat_0.2.1  utf8_1.2.1        crayon_1.4.1   
```
When I look in Livy UI on my cluster: 

![image](https://user-images.githubusercontent.com/13648529/120513446-eb487280-c391-11eb-9037-611f0e29a995.png)

```

// invoke_static(sc, 'org.apache.spark.sql.SparkSession', 'builder', ...) var sparklyrRetVar_0 = sparklyr.LivyUtils.invokeFromBase64("AAAAIm9yZy5hcGFjaGUuc3Bhcmsuc3FsLlNwYXJrU2Vzc2lvbgAAAAABAAAACGJ1aWxkZXIAAAAAAA==") %json sparklyrRetVar_0
--

// invoke_static(sc, 'org.apache.spark.SparkContext', 'getOrCreate', ...) var sparklyrRetVar_1 = sparklyr.LivyUtils.invokeFromBase64("AAAAHm9yZy5hcGFjaGUuc3BhcmsuU3BhcmtDb250ZXh0AAAAAAEAAAAMZ2V0T3JDcmVhdGUAAAAAAA==") %json sparklyrRetVar_1
--

java.lang.OutOfMemoryError: Java heap space
  at sparklyr.Serializer$.readStringBytes(serializer.scala:38)
  at sparklyr.Serializer$.readString(serializer.scala:47)
  at sparklyr.StreamHandler.read(stream.scala:33)
  at sparklyr.LivyUtils$.invokeFromBase64(livyutils.scala:30)
  ... 28 elided

**Comment by yitao-li** [comment]
This seems to be an issue with the Livy cluster you were working with.
The GitHub CI workflow of `sparklyr` runs a number of queries with Livy regularly, and there was never any OutOfMemory error at `spark_connect()` stage, and the `spark_connect()` stack trace you posted doesn't look any different from those in https://github.com/sparklyr/sparklyr/runs/2718278939?check_suite_focus=true or similar workflows.

**Comment by jodom961** [comment]
yeah, I guess the odd thing is I don't get the error/any issue connecting when I use jupyter livy (spark magic) or zeppelin + livy and R in that...  
so the server seems fine, just maybe a weird config issue or error with sparklyr. 

```
`invoke_static(sc, 'org.apache.spark.SparkContext', 'getOrCreate', ...)` 
```
seems to be the command thats failing when I look at my livy server

```
// invoke_static(sc, 'org.apache.spark.sql.SparkSession', 'builder', ...)
sparklyr.LivyUtils.invokeFromBase64("AAAAIm9yZy5hcGFjaGUuc3Bhcmsuc3FsLlNwYXJrU2Vzc2lvbgAAAAABAAAACGJ1aWxkZXIAAAAAAA==")
```

so is the above coming from this jar that i've placed in my hdfs cluster? is that sparklyr jar `sparklyr-2.3-2.11.jar` from the [inst/java](https://github.com/sparklyr/sparklyr/tree/main/inst/java) folder needed?

**Comment by jodom961** [comment]
if i try with the sparklyr 2.4-2.12 jar i get 


`java.lang.NoSuchMethodError: scala.Predef$.byteArrayOps([B)[B   at sparklyr.Serializer$.readStringBytes(serializer.scala:41)   at sparklyr.Serializer$.readString(serializer.scala:47)   at sparklyr.StreamHandler.read(stream.scala:30)   at sparklyr.LivyUtils$.invokeFromBase64(livyutils.scala:34)   ... 50 elided`

**Comment by yitao-li** [comment]
@jodom961 The `scala.Predef$.byteArrayOps([B)[B at...` error seems to indicate a Scala version mismatch (i.e., most likely the Livy server you are working with is built with Scala version 2.11 instead of 2.12).

**Comment by yitao-li** [comment]
Also, start from a fresh R session, setting `options(sparklyr.log.invoke = TRUE)`, and then try `sc <- spark_connect(method = "livy", config = ...)` may be helpful for debugging. You'll be able to see which `invoke()`s succeeded before the failed `invoke()`.
