### ISSUE TITLE
Support for Spark 3.0

### ISSUE THREAD

**Issue by javierluraschi** [sparklyr/sparklyr#1978]
Draft of known TODOs:

1. Add support for installing Spark 3.0 in [here](https://github.com/rstudio/sparklyr/blob/master/inst/extdata/versions.json).
2. Add support to download Scala 2.12 [here](https://github.com/rstudio/sparklyr/blob/master/R/spark_compile.R#L302-L305) by adding an entry for `paste0("https://downloads.lightbend.com/scala/2.12.8/scala-2.12.8.", ext)`, rebuild and run `download_scalac()`.
3. Add a new compilation specification for Spark 3.0 and Scala 2.12 in [here](https://github.com/rstudio/sparklyr/blob/master/R/spark_compile.R#L267-L272). Rebuild.
4. Run `sparklyr::compile_package_jars()`, fix any Scala 2.12, rebuild, repeat 4.

**Comment by lgongmsft** [comment]
@javierluraschi, Regarding the 3rd item on your list, it seems that the compilation specification for Spark 2.4 and Scala 2.11 is also missing [here](https://github.com/rstudio/sparklyr/blob/master/R/spark_compile.R#L267-L272).  I have created an issue for that [here](https://github.com/rstudio/sparklyr/issues/1985#issue-436431038).  Can we fix that first to unblock other sparklyr extensions such as [mleap](https://github.com/rstudio/mleap)?  Thanks!

**Comment by jakubhava** [comment]
@yl790 @javierluraschi Thanks for all the effort!

Just quick question -> Does Sparklyr 1.2 already support Spark 3.0? Since we integrate Spark 3.0 to our Sparkling Water pipelines we are hitting the following error:

> Exception in thread "main" java.lang.NoSuchMethodError: scala.Predef$.refArrayOps([Ljava/lang/Object;)Lscala/collection/mutable/ArrayOps;

Which I suggest is due to the fact that Sparklyr does not yet support Scala 2.12 with Spark 3.0, or am I wrong?

Thanks a lot!

Kuba

**Comment by yl790** [comment]
@jakubhava Sparklyr 1.2 was known to work with Spark 3.0 preview, and most of it works the recently released with Spark 3.0 as well except for the multi-layer perceptron classifier (due to a breaking change in API with Spark 3.0)

The error message you see is usually because sparklyr was trying to submit a jar file built with Scala 2.11 while trying to work with Spark 3.0 built with Scala 2.12 (because the 2 are not binary-compatible)

If you share the full list of parameters you passed to `spark_connect` we'll be able to investigate further.

**Comment by jakubhava** [comment]
Thanks for the quick reply @yl790!

I'm running SparklyR on Kuberentes with the following config:

```
config <- spark_config_kubernetes(master = master,
                                 image = paste0(registryId, ".dkr.ecr.us-east-2.amazonaws.com/sw_kubernetes_repo/sparkling-water:r-", version),
                                 account = "default",
                                 driver ="driver-r",
                                 executors = numExecutors,
                                 conf = extraOptionsParsed,
                                 ports = c(8880, 8881, 4040, 54321))
config["spark.home"] <-  sparkHome
sc <- spark_connect(config = config, spark_home = sparkHome)
```

The error I shared comes from the `driver-r` pod

**Comment by yl790** [comment]
@jakubhava Try connecting with `sc <- spark_connect(config = config, spark_home = sparkHome, version = '3.0.0')`, which should force sparklyr to load the jar file that is actually built for Spark 3.

**Comment by jakubhava** [comment]
Will do, I have added the version specification to the test suite. I Will update in the morning when the tests are done. Thanks for the help!

**Comment by jakubhava** [comment]
The version bit helped, but still not working, the exception now is:

```
 Rscript --default-packages=methods,utils /opt/sparkling-water/tests/initTest.R

Error from server (NotFound): pods "driver-r" not found

Error in force(code) : 

  Failed while connecting to sparklyr to port (8880) for sessionid (27248): Gateway in localhost:8880 did not respond.

    Path: /opt/spark/bin/spark-submit

    Parameters: --master, k8s://https://EE3CDC244111F25217FD02D97C9D5001.yl4.us-east-2.eks.amazonaws.com, --deploy-mode, cluster, --name, sparklyr, --class, sparklyr.Shell, --conf, spark.kubernetes.container.image=524466471676.dkr.ecr.us-east-2.amazonaws.com/sw_kubernetes_repo/sparkling-water:r-3.32.0.1-1-3.0, --conf, spark.kubernetes.driver.pod.name=driver-r, --conf, spark.kubernetes.authenticate.driver.serviceAccountName=default, --conf, spark.executor.instances=2, --jars, '/usr/local/lib/R/site-library/rsparkling/java/sparkling_water_assembly.jar', local:///opt/sparklyr/sparklyr-3.0.0-preview-2.12.jar, 8880, 27248, --remote

    Log: /tmp/RtmpgsN4Lm/file42e7eaa159f_spark.log



---- Output Log ----

20/06/23 22:13:07 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable

Using Spark's default log4j profile: org/apache/spark/log4j-defaults.properties

20/06/23 22:13:07 INFO SparkKubernetesClientFactory: Auto-configuring K8S client using current context from users K8S config file

20/06/23 22:13:08 WARN SSLUtils: SSL handshake failed. Falling back to insecure connection.

20/06/23 22:13:09 WARN SSLUtils: SSL handshake failed. Falling back to insecure connection.

20/06/23 22:13:09 INFO KerberosConfDriverFeatureStep: You have not specified a krb5.conf file locally or via a ConfigMap. Make sure that you have the krb5.conf locally on the driver image.

Exception in thread "main" org.apache.spark.SparkException: Please specify spark.kubernetes.file.upload.path property.

	at org.apache.spark.deploy.k8s.KubernetesUtils$.uploadFileUri(KubernetesUtils.scala:292)

	at org.apache.spark.deploy.k8s.KubernetesUtils$.$anonfun$uploadAndTransformFileUris$1(KubernetesUtils.scala:248)

	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:238)

	at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)

	at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)

	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)

	at scala.collection.TraversableLike.map(TraversableLike.scala:238)

	at scala.collection.TraversableLike.map$(TraversableLike.scala:231)

	at scala.collection.AbstractTraversable.map(Traversable.scala:108)

	at org.apache.spark.deploy.k8s.KubernetesUtils$.uploadAndTransformFileUris(KubernetesUtils.scala:247)

	at org.apache.spark.deploy.k8s.features.BasicDriverFeatureStep.$anonfun$getAdditionalPodSystemProperties$1(BasicDriverFeatureStep.scala:162)

	at scala.collection.immutable.List.foreach(List.scala:392)

	at org.apache.spark.deploy.k8s.features.BasicDriverFeatureStep.getAdditionalPodSystemProperties(BasicDriverFeatureStep.scala:160)

	at org.apache.spark.deploy.k8s.submit.KubernetesDriverBuilder.$anonfun$buildFromFeatures$3(KubernetesDriverBuilder.scala:60)

	at scala.collection.LinearSeqOptimized.foldLeft(LinearSeqOptimized.scala:126)

	at scala.collection.LinearSeqOptimized.foldLeft$(LinearSeqOptimized.scala:122)

	at scala.collection.immutable.List.foldLeft(List.scala:89)

	at org.apache.spark.deploy.k8s.submit.KubernetesDriverBuilder.buildFromFeatures(KubernetesDriverBuilder.scala:58)

	at org.apache.spark.deploy.k8s.submit.Client.run(KubernetesClientApplication.scala:98)

	at org.apache.spark.deploy.k8s.submit.KubernetesClientApplication.$anonfun$run$4(KubernetesClientApplication.scala:221)

	at org.apache.spark.deploy.k8s.submit.KubernetesClientApplication.$anonfun$run$4$adapted(KubernetesClientApplication.scala:215)

	at org.apache.spark.util.Utils$.tryWithResource(Utils.scala:2539)

	at org.apache.spark.deploy.k8s.submit.KubernetesClientApplication.run(KubernetesClientApplication.scala:215)

	at org.apache.spark.deploy.k8s.submit.KubernetesClientApplication.start(KubernetesClientApplication.scala:188)

	at org.apache.spark.deploy.SparkSubmit.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:928)

	at org.apache.spark.deploy.SparkSubmit.doRunMain$1(SparkSubmit.scala:180)

	at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:203)

	at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:90)

	at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:1007)

	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:1016)

	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)

20/06/23 22:13:09 INFO ShutdownHookManager: Shutdown hook called

20/06/23 22:13:09 INFO ShutdownHookManager: Deleting directory /tmp/spark-0d2a9f94-34a4-42b2-b792-d28bc693fe91

```

Just note: the same Kubernetes tests is passing in case of Spark 2.4

**Comment by jakubhava** [comment]
Adding the option ``spark.kubernetes.file.upload.path=file:///tmp`` actually helped and the test is passing now.

**Comment by yl790** [comment]
In related news: after Spark 3.0 recently graced us with its presence, some bits of percepttron-related implementation details in  sparklyr had to be modified to be fully compatible with the new 3.0 API (while continue being compatible with all previous versions of Spark as well, of course).

Please upgrade to sparklyr 1.3 (to be released soon) if you want Spark 3.0 as part of your data workflow.

**Comment by yl790** [comment]
Update: sparklyr 1.3 is released now and fully supports Spark 3.0 as planned.
